name: Flutter CI

on:
  push:
    branches:
      - master # Change this to your project's main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.2' # Use the desired Flutter version
      - name: Install dependencies
        run: flutter pub get

      - name: Build App and debug APK
        run: |
          pushd android 
          flutter build apk
          ./gradlew app:assembleAndroidTest
          ./gradlew app:assembleDebug -Ptarget=${{ github.workspace }}/integration_test/app_test.dart
          popd
      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
      - name: 'Run Tests'
        run: gcloud firebase test android run --type instrumentation --app ${{ github.workspace }}/build/app/outputs/flutter-apk/app-debug.apk --test ${{ github.workspace }}/build/app/outputs/apk/androidTest/debug/app-debug-androidTest.apk
